language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - kcov

after_success:
  - |
    kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/<executable name>-* &&
    bash <(curl -s https://codecov.io/bash) &&
    echo "Uploaded code coverage"

