language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

after_success:
  - |
    travis-cargo --only stable coveralls --no-sudo
