[package]
name = "radix-router"
version = "0.1.0"
authors = ["SunDoge <384813529@qq.com>"]

[dependencies]
hyper = "0.12"
futures = "0.1"
tokio-fs = "0.1"
tokio-io = "0.1"

[dev-dependencies]
pretty_env_logger = "0.2.4"